title: designery by mrmkurtz
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8
  brandStrength: 0.1875
  lightness: 0.5625
  brandColors:
    - '#7b93b9'
    - '#57515f'
    - '#ffdbac'
    - '#3c2726'
    - '#00477a'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: designery
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.62139
layout_spectrum: 0.3617021
