name: designery
favicon: null
layout_spectrum: 0.1946
typography_spectrum: 0.74374
title: designery by mrmkurtz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#172532'
    - '#00a6bc'
    - '#b5b7b4'
    - '#ff615d'
  brandStrength: 0.0625
  lightness: 0.8057168407831341
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
