name: designery
favicon: null
layout_spectrum: 0.17438
typography_spectrum: 0.1474
title: designery by mrmkurtz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#172532'
    - '#00a6bc'
    - '#b5b7b4'
    - '#ff615d'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
