name: designery
favicon: null
layout_spectrum: 0.3087521472480148
typography_spectrum: 0.9654568962287158
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.22238362347707152
  lightness: 0.8057168407831341
  saturation: 0.009572139708325267
  rhythmicContrast: 0.7193759137298912
purpose: []
