name: designery
favicon: null
layout_spectrum: 0.09731
typography_spectrum: 0.62139
title: designery by mrmkurtz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7b93b9'
    - '#57515f'
    - '#ffdbac'
    - '#3c2726'
    - '#00477a'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
